map $http_x_forwarded_port $resolved_port {
    "" $server_port;
    default $http_x_forwarded_port;
}

map $http_x_forwarded_proto $resolved_scheme {
    "" $scheme;
    default $http_x_forwarded_proto;
}

server {
    listen 9001;
    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 10M;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 1000;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 256;
    gzip_vary on;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include fastcgi_params;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param SERVER_PORT $resolved_port;
        fastcgi_param REQUEST_SCHEME $resolved_scheme;
    }

    location ~ /\.ht {
        deny all;
    }
}
