services:
  nginx:
    build:
      target: development
    volumes:
      - ./php:/var/www/html

  php:
    build:
      target: development
    volumes:
      - ./php:/var/www/html

  preact:
    build:
      target: development
    volumes:
      - ./preact:/app
      - /app/node_modules
