services:
  nginx:
    build:
      target: final
    volumes:
      - storage_data:/var/www/html/storage/public:ro
      - ./php/public/dist:/var/www/html/public/dist

  php:
    build:
      target: final
    volumes:
      - storage_data:/var/www/html/storage/public
      - ./php/public/dist:/var/www/html/public/dist
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 5s
      timeout: 3s
      retries: 3

  preact:
    build:
      target: final
