services:
  php:
    build: 
      context: .
      target: ${APP_ENV}
    networks:
      - app-network
    ports:
      - "127.0.0.1:9001:9001"
    container_name: app-php
    restart: always
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/html/storage/public
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          initial_sync: true
          ignore:
            - node_modules/
            - vendor/
            - storage/
            - .git/

  db:
    image: postgres
    container_name: app-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: app-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  storage_data:

networks:
  app-network:
