services:
  proxy:
    build:
      context: ./proxy
      target: ${APP_ENV}
    networks:
      - app-network
    container_name: app-proxy
    ports:
      - "127.0.0.1:9001:9001"
    depends_on:
      php:
        condition: service_started

  php:
    build: 
      context: ./php
      target: ${APP_ENV}
    networks:
      - app-network
    ports:
      - "127.0.0.1:9000:9000"
    container_name: app-php
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/html/storage/public
    develop:
      watch:
        - action: sync
          path: ./php
          target: /var/www/html
          initial_sync: true
          ignore:
            - node_modules/
            - vendor/

  web:
    build:
      context: ./web
      target: ${APP_ENV}
    networks:
      - app-network
    container_name: app-web
    ports:
      - "127.0.0.1:9002:9002"
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
          initial_sync: true
          ignore:
            - node_modules/


  db:
    image: postgres
    container_name: app-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: app-redis
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  storage_data:

networks:
  app-network:
