map $http_x_forwarded_port $resolved_port {
    "" $server_port;
    default $http_x_forwarded_port;
}

map $http_x_forwarded_proto $resolved_scheme {
    "" $scheme;
    default $http_x_forwarded_proto;
}

server {
    listen 9001;
    server_name localhost;
    index index.php;
    client_max_body_size 10M;

    location /admin {
        proxy_pass http://app-php:9000/admin;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $resolved_scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Port $resolved_port;
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-Port $server_port;
        # proxy_set_header X-Forwarded-Host $http_host;
    }

    location / {
        proxy_pass http://app-web:9002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
