; Uploads / requests
upload_max_filesize = 10M
post_max_size = 12M
max_execution_time = 15
max_input_time = 15
memory_limit = 256M

; Error handling
display_errors = Off
log_errors = On
error_log = /proc/self/fd/2

; OPcache
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
opcache.save_comments = 1

; Session
session.gc_maxlifetime = 1440
